projects:
  weatherGraphQLAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: fytlzjshlreeplgpj3cy3qnbmu
        maxDepth: 2
extensions:
  amplify:
    version: 3
